#!/usr/bin/env node
/* Builds docs/icons.js from tools/icons/*.svg (Lucide, ISC license).
 * Run after adding icons:  node tools/make_icons.js
 */
"use strict";
const fs = require("fs");
const path = require("path");

const SRC = path.join(__dirname, "icons");
const OUT = path.join(__dirname, "..", "docs", "icons.js");

const icons = {};
for (const f of fs.readdirSync(SRC).filter(f => f.endsWith(".svg")).sort()) {
  const name = f.replace(".svg", "");
  const svg = fs.readFileSync(path.join(SRC, f), "utf8");
  const inner = svg.slice(svg.indexOf(">", svg.indexOf("<svg")) + 1, svg.lastIndexOf("</svg>"))
    .replace(/<!--[\s\S]*?-->/g, "").replace(/\s+/g, " ").trim();
  icons[name] = inner;
}

fs.writeFileSync(OUT,
  "// Lucide icons (lucide.dev, ISC license) — generated by tools/make_icons.js\n" +
  "const ICONS = " + JSON.stringify(icons) + ";\n" +
  "function icon(name, cls) { return '<svg class=\"icn' + (cls ? ' ' + cls : '') + '\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\">' + ICONS[name] + '</svg>'; }\n");
console.log("OK: icons.js with", Object.keys(icons).length, "icons:", Object.keys(icons).join(", "));
